# Generated by Django 2.2.16 on 2022-11-23 20:30

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Укажите название для категории', max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Задайте уникальный URL адрес категории. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=256, unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Укажите название жанра', max_length=256, verbose_name='Название жанра')),
                ('slug', models.SlugField(help_text='Задайте уникальный URL адрес жанра. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', unique=True, verbose_name='URL жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Укажите название произведения', max_length=256, verbose_name='Название произведения')),
                ('year', models.PositiveSmallIntegerField(help_text='Задайте год выпуска', validators=[api.validators.year_validation], verbose_name='Год выпуска')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('rating', models.IntegerField(default=None, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.Category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(blank=True, related_name='titles', to='titles.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ('-year',),
            },
        ),
    ]
